site_name: AstraEditor Document
site_url: https://docs.astras.top
repo_url: https://github.com/AstraEditor/scratch-gui
repo_name: AstraEditor/scratch-gui

site_description: AstraEditor Document

nav:
  - 主页: index.md
  - 基础: 
    - website/index.md
    - 私有项目不再加载: website/unshared-projects.md
    - 云变量: website/cloud-variables.md
    - 高级设置: 
      - website/settings/overview.md
      - 自定义帧率: website/settings/custom-fps.md
      - 动画插帧: website/settings/interpolation.md
      - 高清画笔: website/settings/high-quality-pen.md
      - 去除舞台边缘: website/settings/remove-fencing.md
      - 去除其他限制: website/settings/remove-misc-limits.md
      - 无限克隆: website/settings/infinite-clones.md
      - 循环计时器: website/settings/warp-timer.md
      - 自定义舞台大小: website/settings/custom-stage-size.md
      - 禁用编译器: website/settings/disable-compiler.md
    - 新编译器: website/new-compiler.md
    - 嵌入作品: website/embedding.md
    - 为啥TW内核这么快?: website/how-it-works.md
    - 怎么下载编译后的JS代码?: website/javascript.md
    - 自定义返回值: website/return.md
    - CORS问题: website/cors.md
    - TW块: website/blocks.md
    - 为TW提供翻译: website/translate.md
    - URL参数: website/url-parameters.md
    - Scratch账户&该编辑器: website/scratch-account.md
    - 捐款: website/donate.md
  - 打包:
    - packager/home.md
    - 嵌入: packager/embedding.md
    - 商业使用: packager/commercial-use.md
    - 动态舞台尺寸: packager/dynamic-stage-resize.md
    - 特殊的云变量: packager/special-cloud-behaviors.md
    - 离线打包器: packager/offline.md

theme: 
  name: material
  custom_dir: overrides
  language: zh
  logo: assets/favicon.ico
  favicon: assets/favicon.ico

  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
    annotation: material/help-circle
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tooltips
    - announce.dismiss
    - content.tabs.link
    - content.code.annotate 

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换为夜间模式
        primary: custom

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换为日间模式
        primary: custom

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      archive_url_date_format: MMMM/dd/yyyy
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 5
      categories_pagination_per_page: 5
  - tags:
      tags_file: blog/tags.md
  - privacy

extra_css:
  - style/style.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

copyright: >
  Copyright &copy; 2025 - present, Astra Team all right reserved.<br>
  <a href="#__consent">修改cookie设置</a>

extra:
  homepage: https://editor.astras.top/document
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/LanwyWriteXU
      name: Cyberexplorer's GitHub
    - icon: fontawesome/brands/bilibili
      link: hhttps://space.bilibili.com/1207841860
      name: Cyberexplorer's Bilibili
    - icon: fontawesome/solid/paper-plane
      link: mailto:zdlanwy@foxmail.com
      name: Cyberexplorer's Email
  consent:
    title: Cookies隐私政策
    description: >- 
      我们使用Cookies(是饼干哦！)来识别您的重复访问和偏好，以及测量我们的文档是否有效以及用户是否找到他们正在搜索的内容。通过您的同意，您正在帮助我们改进我们的文档。
    actions:
      - accept
      - manage
      - reject

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
